spring.application.name=payment-service
server.port=8085

# DATABASE CONFIGURATION (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/paymentdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# KAFKA CONFIGURATION
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# ACTUATOR CONFIGURATION
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always 
